export enum BrainStepType {
  CREATE_REQUISITION = 'CREATE_REQUISITION',
  CREATE_RFQ = 'CREATE_RFQ',
  SELECT_SUPPLIER_QUOTE = 'SELECT_SUPPLIER_QUOTE',
  APPROVE_PURCHASE_ORDER = 'APPROVE_PURCHASE_ORDER',
  RECEIVE_GOODS = 'RECEIVE_GOODS',
  CREATE_AP_BILL = 'CREATE_AP_BILL',
  POST_JOURNAL_ENTRY = 'POST_JOURNAL_ENTRY',
  CREATE_TRANSACTION = 'CREATE_TRANSACTION',
  CREATE_AR_INVOICE = 'CREATE_AR_INVOICE',
  RECORD_PAYMENT = 'RECORD_PAYMENT',
  SEND_NOTIFICATION = 'SEND_NOTIFICATION',
}

export enum BrainChainTemplate {
  REPLENISHMENT_CHAIN = 'REPLENISHMENT_CHAIN',
  INVOICE_CHAIN = 'INVOICE_CHAIN',
  PAYMENT_CHAIN = 'PAYMENT_CHAIN',
}

export enum BrainExecutionStatus {
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum BrainStepStatus {
  PENDING = 'PENDING',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  EXECUTING = 'EXECUTING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  SKIPPED = 'SKIPPED',
}
